# Generated by Django 3.1.6 on 2021-03-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
