# Generated by Django 3.1.6 on 2021-03-27 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='runs_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('runs', models.IntegerField(blank=True)),
                ('balls_face', models.IntegerField(blank=True, null=True)),
                ('strikerate', models.CharField(blank=True, max_length=20)),
                ('sixers', models.IntegerField(blank=True, null=True)),
                ('fours', models.IntegerField(blank=True, null=True)),
                ('opposite_team', models.CharField(blank=True, max_length=100)),
                ('ground', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='balling_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('overs', models.IntegerField()),
                ('maidens', models.IntegerField(blank=True, null=True)),
                ('runs_scored', models.IntegerField(blank=True, null=True)),
                ('wickets', models.IntegerField(blank=True, null=True)),
                ('econ', models.CharField(blank=True, max_length=20)),
                ('average', models.CharField(blank=True, max_length=20)),
                ('opposite_team', models.CharField(blank=True, max_length=100)),
                ('ground', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
