# Generated by Django 3.1.6 on 2021-03-27 05:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='balling_new',
            new_name='balling',
        ),
        migrations.RenameModel(
            old_name='runs_new',
            new_name='runs',
        ),
    ]
