# Generated by Django 3.1.6 on 2021-03-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210327_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runs',
            name='user',
        ),
        migrations.DeleteModel(
            name='balling',
        ),
        migrations.DeleteModel(
            name='runs',
        ),
    ]
