# Generated by Django 3.1.6 on 2021-03-27 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20210327_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('runs', models.IntegerField(blank=True)),
                ('balls_face', models.IntegerField(blank=True, null=True)),
                ('strikerate', models.CharField(blank=True, max_length=20)),
                ('sixers', models.IntegerField(blank=True, null=True)),
                ('fours', models.IntegerField(blank=True, null=True)),
                ('opposite_team', models.CharField(blank=True, max_length=100)),
                ('ground', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
