# Generated by Django 3.1.6 on 2021-03-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_runs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runs',
            old_name='match_id',
            new_name='match_number',
        ),
    ]
