# Generated by Django 3.1.6 on 2021-03-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210327_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='match_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runs',
            name='runs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
