# Generated by Django 3.1.6 on 2021-03-30 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20210327_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='wickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField(null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('maidens', models.IntegerField(blank=True, null=True)),
                ('wickets', models.CharField(blank=True, max_length=20)),
                ('econ', models.CharField(blank=True, max_length=20)),
                ('average', models.CharField(blank=True, max_length=20)),
                ('opposite_team', models.CharField(blank=True, max_length=100)),
                ('ground', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
