# Generated by Django 3.1.6 on 2021-03-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_wickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='wickets',
            name='overs',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
